// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vector_service.proto

#include "vector_service.pb.h"
#include "vector_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace vector {

static const char* VectorService_method_names[] = {
  "/vector.VectorService/SubmitTask",
  "/vector.VectorService/GetResult",
};

std::unique_ptr< VectorService::Stub> VectorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VectorService::Stub> stub(new VectorService::Stub(channel, options));
  return stub;
}

VectorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SubmitTask_(VectorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetResult_(VectorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VectorService::Stub::SubmitTask(::grpc::ClientContext* context, const ::vector::TaskRequest& request, ::vector::TaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vector::TaskRequest, ::vector::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitTask_, context, request, response);
}

void VectorService::Stub::async::SubmitTask(::grpc::ClientContext* context, const ::vector::TaskRequest* request, ::vector::TaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vector::TaskRequest, ::vector::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitTask_, context, request, response, std::move(f));
}

void VectorService::Stub::async::SubmitTask(::grpc::ClientContext* context, const ::vector::TaskRequest* request, ::vector::TaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vector::TaskResponse>* VectorService::Stub::PrepareAsyncSubmitTaskRaw(::grpc::ClientContext* context, const ::vector::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vector::TaskResponse, ::vector::TaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vector::TaskResponse>* VectorService::Stub::AsyncSubmitTaskRaw(::grpc::ClientContext* context, const ::vector::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VectorService::Stub::GetResult(::grpc::ClientContext* context, const ::vector::ResultRequest& request, ::vector::ResultResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vector::ResultRequest, ::vector::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetResult_, context, request, response);
}

void VectorService::Stub::async::GetResult(::grpc::ClientContext* context, const ::vector::ResultRequest* request, ::vector::ResultResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vector::ResultRequest, ::vector::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResult_, context, request, response, std::move(f));
}

void VectorService::Stub::async::GetResult(::grpc::ClientContext* context, const ::vector::ResultRequest* request, ::vector::ResultResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vector::ResultResponse>* VectorService::Stub::PrepareAsyncGetResultRaw(::grpc::ClientContext* context, const ::vector::ResultRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vector::ResultResponse, ::vector::ResultRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vector::ResultResponse>* VectorService::Stub::AsyncGetResultRaw(::grpc::ClientContext* context, const ::vector::ResultRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

VectorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorService::Service, ::vector::TaskRequest, ::vector::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VectorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vector::TaskRequest* req,
             ::vector::TaskResponse* resp) {
               return service->SubmitTask(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorService::Service, ::vector::ResultRequest, ::vector::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VectorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vector::ResultRequest* req,
             ::vector::ResultResponse* resp) {
               return service->GetResult(ctx, req, resp);
             }, this)));
}

VectorService::Service::~Service() {
}

::grpc::Status VectorService::Service::SubmitTask(::grpc::ServerContext* context, const ::vector::TaskRequest* request, ::vector::TaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VectorService::Service::GetResult(::grpc::ServerContext* context, const ::vector::ResultRequest* request, ::vector::ResultResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vector
#include <grpcpp/ports_undef.inc>

