// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vector_service.proto
// Protobuf C++ Version: 5.29.3

#include "vector_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace vector {

inline constexpr TaskResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TaskResponse::TaskResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TaskResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskResponseDefaultTypeInternal() {}
  union {
    TaskResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskResponseDefaultTypeInternal _TaskResponse_default_instance_;

inline constexpr TaskRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : vector_{},
        job_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        task_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TaskRequest::TaskRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TaskRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskRequestDefaultTypeInternal() {}
  union {
    TaskRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskRequestDefaultTypeInternal _TaskRequest_default_instance_;

inline constexpr ResultResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{},
        job_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        completed_slices_{0},
        total_slices_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResultResponse::ResultResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResultResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResultResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResultResponseDefaultTypeInternal() {}
  union {
    ResultResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResultResponseDefaultTypeInternal _ResultResponse_default_instance_;

inline constexpr ResultRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : job_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResultRequest::ResultRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResultRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResultRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResultRequestDefaultTypeInternal() {}
  union {
    ResultRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResultRequestDefaultTypeInternal _ResultRequest_default_instance_;
}  // namespace vector
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_vector_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_vector_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_vector_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::vector::TaskRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector::TaskRequest, _impl_.job_id_),
        PROTOBUF_FIELD_OFFSET(::vector::TaskRequest, _impl_.task_),
        PROTOBUF_FIELD_OFFSET(::vector::TaskRequest, _impl_.vector_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::vector::TaskResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector::TaskResponse, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::vector::TaskResponse, _impl_.result_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::vector::ResultRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector::ResultRequest, _impl_.job_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::vector::ResultResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector::ResultResponse, _impl_.job_id_),
        PROTOBUF_FIELD_OFFSET(::vector::ResultResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::vector::ResultResponse, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::vector::ResultResponse, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::vector::ResultResponse, _impl_.completed_slices_),
        PROTOBUF_FIELD_OFFSET(::vector::ResultResponse, _impl_.total_slices_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::vector::TaskRequest)},
        {11, -1, -1, sizeof(::vector::TaskResponse)},
        {21, -1, -1, sizeof(::vector::ResultRequest)},
        {30, -1, -1, sizeof(::vector::ResultResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::vector::_TaskRequest_default_instance_._instance,
    &::vector::_TaskResponse_default_instance_._instance,
    &::vector::_ResultRequest_default_instance_._instance,
    &::vector::_ResultResponse_default_instance_._instance,
};
const char descriptor_table_protodef_vector_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024vector_service.proto\022\006vector\";\n\013TaskRe"
    "quest\022\016\n\006job_id\030\001 \001(\t\022\014\n\004task\030\002 \001(\t\022\016\n\006v"
    "ector\030\003 \003(\002\"/\n\014TaskResponse\022\017\n\007message\030\001"
    " \001(\t\022\016\n\006result\030\002 \003(\002\"\037\n\rResultRequest\022\016\n"
    "\006job_id\030\001 \001(\t\"\201\001\n\016ResultResponse\022\016\n\006job_"
    "id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\016\n\006result\030\003 \003(\002"
    "\022\017\n\007message\030\004 \001(\t\022\030\n\020completed_slices\030\005 "
    "\001(\005\022\024\n\014total_slices\030\006 \001(\0052\204\001\n\rVectorServ"
    "ice\0227\n\nSubmitTask\022\023.vector.TaskRequest\032\024"
    ".vector.TaskResponse\022:\n\tGetResult\022\025.vect"
    "or.ResultRequest\032\026.vector.ResultResponse"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_vector_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_vector_5fservice_2eproto = {
    false,
    false,
    448,
    descriptor_table_protodef_vector_5fservice_2eproto,
    "vector_service.proto",
    &descriptor_table_vector_5fservice_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_vector_5fservice_2eproto::offsets,
    file_level_enum_descriptors_vector_5fservice_2eproto,
    file_level_service_descriptors_vector_5fservice_2eproto,
};
namespace vector {
// ===================================================================

class TaskRequest::_Internal {
 public:
};

TaskRequest::TaskRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector.TaskRequest)
}
inline PROTOBUF_NDEBUG_INLINE TaskRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector::TaskRequest& from_msg)
      : vector_{visibility, arena, from.vector_},
        job_id_(arena, from.job_id_),
        task_(arena, from.task_),
        _cached_size_{0} {}

TaskRequest::TaskRequest(
    ::google::protobuf::Arena* arena,
    const TaskRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TaskRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:vector.TaskRequest)
}
inline PROTOBUF_NDEBUG_INLINE TaskRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : vector_{visibility, arena},
        job_id_(arena),
        task_(arena),
        _cached_size_{0} {}

inline void TaskRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TaskRequest::~TaskRequest() {
  // @@protoc_insertion_point(destructor:vector.TaskRequest)
  SharedDtor(*this);
}
inline void TaskRequest::SharedDtor(MessageLite& self) {
  TaskRequest& this_ = static_cast<TaskRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.job_id_.Destroy();
  this_._impl_.task_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TaskRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TaskRequest(arena);
}
constexpr auto TaskRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.vector_) +
          decltype(TaskRequest::_impl_.vector_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TaskRequest), alignof(TaskRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TaskRequest::PlacementNew_,
                                 sizeof(TaskRequest),
                                 alignof(TaskRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TaskRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TaskRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TaskRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TaskRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TaskRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TaskRequest>(), &TaskRequest::ByteSizeLong,
            &TaskRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_._cached_size_),
        false,
    },
    &TaskRequest::kDescriptorMethods,
    &descriptor_table_vector_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TaskRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 37, 2> TaskRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector::TaskRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string job_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.job_id_)}},
    // string task = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.task_)}},
    // repeated float vector = 3;
    {::_pbi::TcParser::FastF32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.vector_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string job_id = 1;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.job_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string task = 2;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.task_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated float vector = 3;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.vector_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
    "\22\6\4\0\0\0\0\0"
    "vector.TaskRequest"
    "job_id"
    "task"
  }},
};

PROTOBUF_NOINLINE void TaskRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:vector.TaskRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.vector_.Clear();
  _impl_.job_id_.ClearToEmpty();
  _impl_.task_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TaskRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TaskRequest& this_ = static_cast<const TaskRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TaskRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TaskRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector.TaskRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string job_id = 1;
          if (!this_._internal_job_id().empty()) {
            const std::string& _s = this_._internal_job_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vector.TaskRequest.job_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string task = 2;
          if (!this_._internal_task().empty()) {
            const std::string& _s = this_._internal_task();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vector.TaskRequest.task");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated float vector = 3;
          if (this_._internal_vector_size() > 0) {
            target = stream->WriteFixedPacked(3, this_._internal_vector(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector.TaskRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TaskRequest::ByteSizeLong(const MessageLite& base) {
          const TaskRequest& this_ = static_cast<const TaskRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TaskRequest::ByteSizeLong() const {
          const TaskRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector.TaskRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated float vector = 3;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_vector_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
          }
           {
            // string job_id = 1;
            if (!this_._internal_job_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_job_id());
            }
            // string task = 2;
            if (!this_._internal_task().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_task());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TaskRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TaskRequest*>(&to_msg);
  auto& from = static_cast<const TaskRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector.TaskRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_vector()->MergeFrom(from._internal_vector());
  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_task().empty()) {
    _this->_internal_set_task(from._internal_task());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TaskRequest::CopyFrom(const TaskRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector.TaskRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TaskRequest::InternalSwap(TaskRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.vector_.InternalSwap(&other->_impl_.vector_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.job_id_, &other->_impl_.job_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.task_, &other->_impl_.task_, arena);
}

::google::protobuf::Metadata TaskRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TaskResponse::_Internal {
 public:
};

TaskResponse::TaskResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector.TaskResponse)
}
inline PROTOBUF_NDEBUG_INLINE TaskResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector::TaskResponse& from_msg)
      : result_{visibility, arena, from.result_},
        message_(arena, from.message_),
        _cached_size_{0} {}

TaskResponse::TaskResponse(
    ::google::protobuf::Arena* arena,
    const TaskResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TaskResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:vector.TaskResponse)
}
inline PROTOBUF_NDEBUG_INLINE TaskResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : result_{visibility, arena},
        message_(arena),
        _cached_size_{0} {}

inline void TaskResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TaskResponse::~TaskResponse() {
  // @@protoc_insertion_point(destructor:vector.TaskResponse)
  SharedDtor(*this);
}
inline void TaskResponse::SharedDtor(MessageLite& self) {
  TaskResponse& this_ = static_cast<TaskResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TaskResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TaskResponse(arena);
}
constexpr auto TaskResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.result_) +
          decltype(TaskResponse::_impl_.result_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TaskResponse), alignof(TaskResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TaskResponse::PlacementNew_,
                                 sizeof(TaskResponse),
                                 alignof(TaskResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TaskResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TaskResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TaskResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TaskResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TaskResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TaskResponse>(), &TaskResponse::ByteSizeLong,
            &TaskResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_._cached_size_),
        false,
    },
    &TaskResponse::kDescriptorMethods,
    &descriptor_table_vector_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TaskResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 35, 2> TaskResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector::TaskResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated float result = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.result_)}},
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated float result = 2;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
    "\23\7\0\0\0\0\0\0"
    "vector.TaskResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void TaskResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:vector.TaskResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.Clear();
  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TaskResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TaskResponse& this_ = static_cast<const TaskResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TaskResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TaskResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector.TaskResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string message = 1;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vector.TaskResponse.message");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated float result = 2;
          if (this_._internal_result_size() > 0) {
            target = stream->WriteFixedPacked(2, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector.TaskResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TaskResponse::ByteSizeLong(const MessageLite& base) {
          const TaskResponse& this_ = static_cast<const TaskResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TaskResponse::ByteSizeLong() const {
          const TaskResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector.TaskResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated float result = 2;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_result_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
          }
           {
            // string message = 1;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TaskResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TaskResponse*>(&to_msg);
  auto& from = static_cast<const TaskResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector.TaskResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_result()->MergeFrom(from._internal_result());
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TaskResponse::CopyFrom(const TaskResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector.TaskResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TaskResponse::InternalSwap(TaskResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_.InternalSwap(&other->_impl_.result_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata TaskResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResultRequest::_Internal {
 public:
};

ResultRequest::ResultRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector.ResultRequest)
}
inline PROTOBUF_NDEBUG_INLINE ResultRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector::ResultRequest& from_msg)
      : job_id_(arena, from.job_id_),
        _cached_size_{0} {}

ResultRequest::ResultRequest(
    ::google::protobuf::Arena* arena,
    const ResultRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResultRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:vector.ResultRequest)
}
inline PROTOBUF_NDEBUG_INLINE ResultRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : job_id_(arena),
        _cached_size_{0} {}

inline void ResultRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ResultRequest::~ResultRequest() {
  // @@protoc_insertion_point(destructor:vector.ResultRequest)
  SharedDtor(*this);
}
inline void ResultRequest::SharedDtor(MessageLite& self) {
  ResultRequest& this_ = static_cast<ResultRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.job_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ResultRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResultRequest(arena);
}
constexpr auto ResultRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResultRequest),
                                            alignof(ResultRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResultRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResultRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResultRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResultRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResultRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResultRequest>(), &ResultRequest::ByteSizeLong,
            &ResultRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResultRequest, _impl_._cached_size_),
        false,
    },
    &ResultRequest::kDescriptorMethods,
    &descriptor_table_vector_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResultRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 35, 2> ResultRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector::ResultRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string job_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResultRequest, _impl_.job_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string job_id = 1;
    {PROTOBUF_FIELD_OFFSET(ResultRequest, _impl_.job_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\6\0\0\0\0\0\0"
    "vector.ResultRequest"
    "job_id"
  }},
};

PROTOBUF_NOINLINE void ResultRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:vector.ResultRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResultRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResultRequest& this_ = static_cast<const ResultRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResultRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResultRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector.ResultRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string job_id = 1;
          if (!this_._internal_job_id().empty()) {
            const std::string& _s = this_._internal_job_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vector.ResultRequest.job_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector.ResultRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResultRequest::ByteSizeLong(const MessageLite& base) {
          const ResultRequest& this_ = static_cast<const ResultRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResultRequest::ByteSizeLong() const {
          const ResultRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector.ResultRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string job_id = 1;
            if (!this_._internal_job_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_job_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResultRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResultRequest*>(&to_msg);
  auto& from = static_cast<const ResultRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector.ResultRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResultRequest::CopyFrom(const ResultRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector.ResultRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResultRequest::InternalSwap(ResultRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.job_id_, &other->_impl_.job_id_, arena);
}

::google::protobuf::Metadata ResultRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResultResponse::_Internal {
 public:
};

ResultResponse::ResultResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector.ResultResponse)
}
inline PROTOBUF_NDEBUG_INLINE ResultResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector::ResultResponse& from_msg)
      : result_{visibility, arena, from.result_},
        job_id_(arena, from.job_id_),
        status_(arena, from.status_),
        message_(arena, from.message_),
        _cached_size_{0} {}

ResultResponse::ResultResponse(
    ::google::protobuf::Arena* arena,
    const ResultResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResultResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, completed_slices_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, completed_slices_),
           offsetof(Impl_, total_slices_) -
               offsetof(Impl_, completed_slices_) +
               sizeof(Impl_::total_slices_));

  // @@protoc_insertion_point(copy_constructor:vector.ResultResponse)
}
inline PROTOBUF_NDEBUG_INLINE ResultResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : result_{visibility, arena},
        job_id_(arena),
        status_(arena),
        message_(arena),
        _cached_size_{0} {}

inline void ResultResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, completed_slices_),
           0,
           offsetof(Impl_, total_slices_) -
               offsetof(Impl_, completed_slices_) +
               sizeof(Impl_::total_slices_));
}
ResultResponse::~ResultResponse() {
  // @@protoc_insertion_point(destructor:vector.ResultResponse)
  SharedDtor(*this);
}
inline void ResultResponse::SharedDtor(MessageLite& self) {
  ResultResponse& this_ = static_cast<ResultResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.job_id_.Destroy();
  this_._impl_.status_.Destroy();
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ResultResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResultResponse(arena);
}
constexpr auto ResultResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.result_) +
          decltype(ResultResponse::_impl_.result_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ResultResponse), alignof(ResultResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ResultResponse::PlacementNew_,
                                 sizeof(ResultResponse),
                                 alignof(ResultResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResultResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResultResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResultResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResultResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResultResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResultResponse>(), &ResultResponse::ByteSizeLong,
            &ResultResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_._cached_size_),
        false,
    },
    &ResultResponse::kDescriptorMethods,
    &descriptor_table_vector_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResultResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 49, 2> ResultResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector::ResultResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string job_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.job_id_)}},
    // string status = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.status_)}},
    // repeated float result = 3;
    {::_pbi::TcParser::FastF32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.result_)}},
    // string message = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.message_)}},
    // int32 completed_slices = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResultResponse, _impl_.completed_slices_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.completed_slices_)}},
    // int32 total_slices = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResultResponse, _impl_.total_slices_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.total_slices_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string job_id = 1;
    {PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.job_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string status = 2;
    {PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated float result = 3;
    {PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // string message = 4;
    {PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 completed_slices = 5;
    {PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.completed_slices_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 total_slices = 6;
    {PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.total_slices_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\25\6\6\0\7\0\0\0"
    "vector.ResultResponse"
    "job_id"
    "status"
    "message"
  }},
};

PROTOBUF_NOINLINE void ResultResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:vector.ResultResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.Clear();
  _impl_.job_id_.ClearToEmpty();
  _impl_.status_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  ::memset(&_impl_.completed_slices_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.total_slices_) -
      reinterpret_cast<char*>(&_impl_.completed_slices_)) + sizeof(_impl_.total_slices_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResultResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResultResponse& this_ = static_cast<const ResultResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResultResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResultResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector.ResultResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string job_id = 1;
          if (!this_._internal_job_id().empty()) {
            const std::string& _s = this_._internal_job_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vector.ResultResponse.job_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string status = 2;
          if (!this_._internal_status().empty()) {
            const std::string& _s = this_._internal_status();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vector.ResultResponse.status");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated float result = 3;
          if (this_._internal_result_size() > 0) {
            target = stream->WriteFixedPacked(3, this_._internal_result(), target);
          }

          // string message = 4;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "vector.ResultResponse.message");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // int32 completed_slices = 5;
          if (this_._internal_completed_slices() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<5>(
                    stream, this_._internal_completed_slices(), target);
          }

          // int32 total_slices = 6;
          if (this_._internal_total_slices() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_total_slices(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector.ResultResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResultResponse::ByteSizeLong(const MessageLite& base) {
          const ResultResponse& this_ = static_cast<const ResultResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResultResponse::ByteSizeLong() const {
          const ResultResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector.ResultResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated float result = 3;
            {
              std::size_t data_size = std::size_t{4} *
                  ::_pbi::FromIntSize(this_._internal_result_size());
              std::size_t tag_size = data_size == 0
                  ? 0
                  : 1 + ::_pbi::WireFormatLite::Int32Size(
                                      static_cast<int32_t>(data_size));
              total_size += tag_size + data_size;
            }
          }
           {
            // string job_id = 1;
            if (!this_._internal_job_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_job_id());
            }
            // string status = 2;
            if (!this_._internal_status().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_status());
            }
            // string message = 4;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // int32 completed_slices = 5;
            if (this_._internal_completed_slices() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_completed_slices());
            }
            // int32 total_slices = 6;
            if (this_._internal_total_slices() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_total_slices());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResultResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResultResponse*>(&to_msg);
  auto& from = static_cast<const ResultResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector.ResultResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_result()->MergeFrom(from._internal_result());
  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_completed_slices() != 0) {
    _this->_impl_.completed_slices_ = from._impl_.completed_slices_;
  }
  if (from._internal_total_slices() != 0) {
    _this->_impl_.total_slices_ = from._impl_.total_slices_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResultResponse::CopyFrom(const ResultResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector.ResultResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResultResponse::InternalSwap(ResultResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_.InternalSwap(&other->_impl_.result_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.job_id_, &other->_impl_.job_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, &other->_impl_.status_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.total_slices_)
      + sizeof(ResultResponse::_impl_.total_slices_)
      - PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.completed_slices_)>(
          reinterpret_cast<char*>(&_impl_.completed_slices_),
          reinterpret_cast<char*>(&other->_impl_.completed_slices_));
}

::google::protobuf::Metadata ResultResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace vector
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_vector_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
